version: 0.2

phases:
  install:
    commands:
      - java -version
      - rpm --import https://yum.corretto.aws/corretto.key
      - curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo
      - yum install -y java-17-amazon-corretto-devel
      - alternatives --display java
      - alternatives --set /usr/lib/jvm/java-17-amazon-corretto/bin/java
      - java -version
  build:
    commands:
      - ls -l
      - chmod +x gradlew
      - ./gradlew bootJar
      - mv build/libs/minimal-container-*.jar minimal-container.jar
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 320979466941.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker build -t minimal-container:latest .
      - docker tag shiontkkg/minimal-container:latest 320979466941.dkr.ecr.ap-northeast-1.amazonaws.com/minimal-container:latest
  post_build:
    commands:
      - docker push 320979466941.dkr.ecr.ap-northeast-1.amazonaws.com/minimal-container:latest
